[theme]
# Primary accent color for interactive elements.
primaryColor = "black"

# Background color for the main content area.
backgroundColor = "white"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "lightgrey"

# Color used for almost all text.
textColor = "black"